# This workflow will lint and check for vulnerabilities in our flask app

name: Pipeline for Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Set Up Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8 ./app.py

    - name: Set Up Safety
      run: pip install safety

    - name: Authorize Safety and scan
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_TOKEN }}

    - name: Install bandit
      run: pip install bandit
    - name: Run bandit
      run: bandit -r .
